# Generated by Django 5.0.6 on 2024-06-27 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apm_categories', '0004_ashpenserpaymentmethod_ashpensersubcategories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ashpensercategories',
            name='date_created',
            field=models.DateTimeField(blank=True, max_length=8, null=True),
        ),
    ]
