# Generated by Django 5.0.6 on 2024-06-30 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apm_earnings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ashpenserearnings',
            name='date',
            field=models.DateField(),
        ),
    ]
