# Generated by Django 4.2 on 2023-04-20 16:49

from django.db import migrations, models
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MembersData',
            fields=[
                ('member_data', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=50, verbose_name='last name')),
                ('first_name', models.CharField(max_length=50, verbose_name='first name')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, verbose_name='gender')),
                ('date_of_birth', models.DateField(max_length=8, verbose_name='birth date')),
                ('age', models.PositiveIntegerField(verbose_name='age')),
                ('postal_address', models.CharField(blank=True, max_length=50, null=True, verbose_name='postal address')),
                ('email_address', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email address')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='phone number')),
                ('created_at', models.DateField()),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, default='default/default.png', null=True, upload_to='members/')),
            ],
        ),
    ]
