# Generated by Django 4.2 on 2023-04-20 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membersdata',
            options={'ordering': ('last_name',), 'verbose_name_plural': 'MembersData'},
        ),
        migrations.AlterModelTable(
            name='membersdata',
            table='members_data',
        ),
    ]
