# Generated by Django 4.2 on 2023-04-20 17:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_membersdata_options_alter_membersdata_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membersdata',
            name='created_at',
            field=models.DateField(verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='membersdata',
            name='updated_at',
            field=models.DateField(default=datetime.date(2023, 4, 20)),
        ),
    ]
