# Generated by Django 4.2 on 2023-04-20 17:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_alter_membersdata_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membersdata',
            name='created_at',
            field=models.DateField(max_length=8, verbose_name='current date'),
        ),
        migrations.AlterField(
            model_name='membersdata',
            name='updated_at',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
