# Generated by Django 4.2 on 2023-04-25 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_alter_membersdata_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membersdata',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=8, verbose_name='gender'),
        ),
    ]
