# Generated by Django 5.0.6 on 2024-07-05 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apm_accounts', '0002_alter_ashpenser_email_alter_ashpenser_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ashpenser',
            name='image',
        ),
        migrations.RemoveField(
            model_name='ashpenser',
            name='security_answer',
        ),
        migrations.RemoveField(
            model_name='ashpenser',
            name='security_question',
        ),
    ]
