# Generated by Django 5.0.6 on 2024-07-05 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apm_accounts', '0004_alter_ashpenser_options_alter_ashpenser_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='ashpenser',
            name='firstname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ashpenser',
            name='image',
            field=models.ImageField(default='default/default.png', max_length=255, upload_to='apmenser/'),
        ),
        migrations.AddField(
            model_name='ashpenser',
            name='lastname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ashpenser',
            name='mfa_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ashpenser',
            name='security_answer',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='ashpenser',
            name='security_question',
            field=models.CharField(blank=True, choices=[('Pet name', 'What was the name of your first pet?'), ('Street name', 'What is the street name of the second place you lived?'), ('Favourite book', 'What was the title of your childhood favourite book?'), ('Maternal grandmother', "What is your maternal grandmother's maiden name?"), ('Grade school mentor', 'What was the last name of your grade school mentor?')], max_length=255, null=True),
        ),
    ]
