# Generated by Django 5.0.6 on 2024-07-08 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apm_accounts', '0005_ashpenser_firstname_ashpenser_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ashpenser',
            name='image',
        ),
        migrations.RemoveField(
            model_name='ashpenser',
            name='mfa_enabled',
        ),
    ]
