# Generated by Django 5.0.6 on 2024-07-03 20:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ASHPensersProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ashpenser_image', models.ImageField(default='default/default.png', max_length=255, upload_to='apmenser/')),
                ('ashpenser_mfa', models.BooleanField(default=False)),
                ('ashpenser_lastname', models.CharField(blank=True, max_length=50, null=True)),
                ('ashpenser_firstname', models.CharField(blank=True, max_length=50, null=True)),
                ('ashpenser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
