# Generated by Django 5.0.6 on 2024-07-05 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ashpensers', '0002_rename_ashpenser_firstname_ashpensersprofile_firstname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ashpensersprofile',
            old_name='firstname',
            new_name='ashpenser_firstname',
        ),
        migrations.RenameField(
            model_name='ashpensersprofile',
            old_name='image',
            new_name='ashpenser_image',
        ),
        migrations.RenameField(
            model_name='ashpensersprofile',
            old_name='lastname',
            new_name='ashpenser_lastname',
        ),
        migrations.RenameField(
            model_name='ashpensersprofile',
            old_name='mfa',
            new_name='ashpenser_mfa',
        ),
    ]
