# Generated by Django 5.0.6 on 2024-07-08 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ashpensers', '0006_alter_ashpensersprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ashpensersprofile',
            options={'verbose_name_plural': 'ASHPensersProfile'},
        ),
        migrations.RenameField(
            model_name='ashpensersprofile',
            old_name='mfa',
            new_name='mfa_enabled',
        ),
        migrations.RemoveField(
            model_name='ashpensersprofile',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='ashpensersprofile',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='ashpensersprofile',
            name='security_answer',
        ),
        migrations.RemoveField(
            model_name='ashpensersprofile',
            name='security_question',
        ),
    ]
