# Generated by Django 5.0.6 on 2024-07-08 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ashpensers', '0007_alter_ashpensersprofile_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ashpensersprofile',
            name='mfa_enabled',
        ),
        migrations.AddField(
            model_name='ashpensersprofile',
            name='bio',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
